version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:80"           
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:pass@db:5432/medrec

  db:
    image: postgres:17      
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=medrec
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
