"""Add doctor_id to patients

Revision ID: 3b04a438e3ae
Revises: 4185cc3803a8
Create Date: 2025-09-10 18:28:37.794548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b04a438e3ae'
down_revision: Union[str, Sequence[str], None] = '4185cc3803a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patients', 'doctors', ['doctor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'doctor_id')
    # ### end Alembic commands ###
